apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-2
  namespace: argocd
spec:
  destination:
    server: microk8s
  project: default
  source:
    path: mineOps/files/ArgoCD/appofapps/mineops-servers/customer-2
    repoURL: https://github.com/danquill/ops-demos.git
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
