apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-1
  namespace: argocd
spec:
  destination:
    server: https://192.168.64.5:16443
    namespace: mineops-1
  project: default
  source:
    path: mineOps/files/ArgoCD/appofapps/mineops-servers/customer-1
    repoURL: https://github.com/danquill/ops-demos.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true