apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-0
  namespace: openshift-gitops
spec:
  destination:
    server: https://api.crc.testing:6443
    namespace: mineops-0
  project: default
  source:
    path: charts/minecraft
    repoURL: https://github.com/itzg/minecraft-server-charts.git
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true