affinity: {}
deploymentAnnotations: {}
deploymentLabels: {}
envFrom: []
extraDeploy: []
extraEnv: {}
extraPodSpec: {}
extraVolumes: []
image:
  pullPolicy: Always
  pullSecret: ""
  repository: itzg/minecraft-server
  tag: latest
initContainers: []
lifecycle:
  postStart: []
  preStop: []
livenessProbe:
  command:
  - mc-health
  failureThreshold: 20
  initialDelaySeconds: 30
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1
mcbackup:
  backupInterval: 24h
  backupMethod: tar
  compressMethod: gzip
  destDir: /backups
  enabled: true
  envFrom: []
  excludes: '*.jar,cache,logs'
  extraEnv: {}
  image:
    pullPolicy: IfNotPresent
    repository: itzg/mc-backup
    tag: latest
  initialDelay: 2m
  linkLatest: "false"
  pauseIfNoPlayers: "false"
  persistence:
    annotations: {}
    backupDir:
      Size: 1Gi
      accessModes:
      - ReadWriteOnce
      enabled: true
      existingClaim: minecraft-backup-pvc
  pruneBackupsDays: 7
  pruneResticRetention: --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly
    75
  rcloneCompressMethod: gzip
  rcloneConfig: null
  rcloneDestDir: null
  rcloneRemote: null
  rconRetries: 5
  rconRetryInterval: 10s
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
  resticAdditionalTags: mc_backups
  resticEnvs: {}
  resticRepository: ""
  zstdParameters: -3 --long=25 --single-thread
minecraftServer:
  allowNether: default
  announcePlayerAchievements: default
  autoCurseForge:
    apiKey:
      existingSecret: ""
      key: CHANGEME!
      secretKey: cf-api-key
    excludeIncludeFile: null
    excludeMods: []
    fileId: ""
    filenameMatcher: ""
    forceSynchronize: false
    includeMods: []
    overridesSkipExisting: false
    pageUrl: ""
    parallelDownloads: 4
    setLevelFrom: ""
    slug: ""
  bukkitDownloadUrl: null
  cfServerMod: null
  clusterIP: null
  difficulty: normal
  downloadModpackUrl: null
  downloadWorldUrl: null
  enableCommandBlock: default
  enforceSecureProfile: default
  eula: "TRUE"
  externalIPs: null
  extraPorts: []
  extraServiceSpec: {}
  forceReDownload: false
  forcegameMode: default
  forgeInstallerUrl: null
  forgeVersion: null
  ftbLegacyJavaFixer: default
  ftbModpackId: null
  ftbModpackVersionId: null
  gameMode: survival
  generateStructures: default
  generatorSettings: null
  hardcore: default
  icon: null
  jvmOpts: ""
  jvmXXOpts: ""
  levelSeed: null
  levelType: DEFAULT
  loadBalancerClass: null
  loadBalancerIP: null
  maxBuildHeight: default
  maxPlayers: default
  maxTickTime: default
  maxWorldSize: default
  memory: 1024M
  modUrls: []
  modrinth:
    allowedVersionType: default
    optionalDependencies: false
    projects: []
  motd: Welcome to Minecraft on Kubernetes!
  nodePort: null
  onlineMode: default
  ops: null
  overrideServerProperties: default
  paperDownloadUrl: null
  pluginUrls: []
  pvp: default
  query:
    enabled: false
    port: 25565
  rcon:
    clusterIP: null
    enabled: true
    existingSecret: null
    loadBalancerClass: null
    loadBalancerIP: null
    nodePort: null
    password: rconpassword!
    port: 25575
    secretKey: rcon-password
    serviceType: ClusterIP
    withGeneratedPassword: false
  removeOldMods: false
  resourcePackEnforce: false
  resourcePackSha: null
  resourcePackUrl: null
  serviceAnnotations: {}
  servicePort: 25565
  serviceType: ClusterIP
  spawnAnimals: default
  spawnMonsters: default
  spawnNPCs: default
  spawnProtection: default
  spigetResources: []
  spigotDownloadUrl: null
  spongeVersion: null
  tty: true
  type: VANILLA
  vanillaTweaksShareCodes: []
  version: LATEST
  viewDistance: default
  whitelist: null
  worldSaveName: world
nodeSelector: {}
persistence:
  annotations: {}
  dataDir:
    Size: 1Gi
    accessModes:
    - ReadWriteOnce
    enabled: true
    existingClaim: minecraft-data-pvc
  labels: {}
podAnnotations:
  backup.velero.io/backup-volumes: backupdir,datadir
podLabels:
  name: minecraft
podSecurityContext:
  fsGroup: 1000730000
  runAsGroup: 1000730000
  runAsNonRoot: true
  runAsUser: 1000730000
  seccompProfile:
    type: RuntimeDefault
rconServiceAnnotations: {}
rconServiceLabels: {}
readinessProbe:
  command:
  - mc-health
  failureThreshold: 20
  initialDelaySeconds: 30
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1
replicaCount: 1
resources:
  requests:
    cpu: 500m
    memory: 512Mi
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
serviceAnnotations: {}
serviceLabels: {}
sidecarContainers: []
startupProbe:
  command:
  - mc-health
  enabled: false
  failureThreshold: 30
  periodSeconds: 10
strategyType: Recreate
tolerations: []
workloadAsStatefulSet: false
