apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mineops
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          cluster-type: "remote"
  template:
    metadata:
      name: '{{.name}}-mineops' # 'name' field of the Secret
    spec:
      project: "default"
      sources:
        - repoURL: https://itzg.github.io/minecraft-server-charts/
          chart: minecraft
          targetRevision: 4.23.7
          helm:
            valueFiles:
              - $value/mineOps/values/{{.name}}/minecraft-values.yaml
        - repoURL: https://github.com/danquill/ops-demos.git
          targetRevision: main
          ref: value 
      destination:
        server: '{{.server}}' # 'server' field of the secret
        namespace: '{{.name}}-mineops'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true