apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mineops
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          cluster-type: "remote"
  template:
    metadata:
      name: '{{.name}}-mineops' # 'name' field of the Secret
    spec:
      project: "default"
      source:
        repoURL: https://github.com/itzg/minecraft-server-charts.git
        targetRevision: master
        path: charts/minecraft
       
      destination:
        server: '{{.server}}' # 'server' field of the secret