---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mineops
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 5Gi 
---
apiVersion: v1
kind: Pod
metadata:
  name: customer-init
spec:
  containers:
  - name: data-grabber
    image: registry.access.redhat.com/ubi8/ubi:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: mineops-pvc
      mountPath: /mineops-data
  volumes:
  - name: mineops-pvc
    persistentVolumeClaim:
      claimName: mineops
