apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-minecraft
spec:
  project: default
  source:
    chart: minecraft
    repoURL: https://itzg.github.io/minecraft-server-charts/
  destination:
    server: https://api.crc.testing:6443
    namespace: helm-minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true